from .settings import *
ALLOWED_HOSTS = ['*']
# DATABASE
POSBYS_DATABASE_NAME = os.getenv('POSBYS_DATABASE_NAME', 'byspos')
POSBYS_DATABASE_HOST = os.getenv('POSBYS_DATABASE_HOST', '131.0.0.245')
POSBYS_DATABASE_PORT = os.getenv('POSBYS_DATABASE_PORT', '5432')
POSBYS_DATABASE_USER = os.getenv('POSBYS_DATABASE_USER', 'postgres')
POSBYS_DATABASE_PASSWORD = os.getenv('POSBYS_DATABASE_PASSWORD', 'byspos')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': POSBYS_DATABASE_NAME,
        'USER': POSBYS_DATABASE_USER,
        'PASSWORD': POSBYS_DATABASE_PASSWORD,
        'HOST': POSBYS_DATABASE_HOST,
        'PORT': POSBYS_DATABASE_PORT,
        'CHARSET': 'UTF8',
    },
}

CORS_ORIGIN_ALLOW_ALL = True
