# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('acciones', models.ManyToManyField(to='posbys_config.Acciones')),
            ],
        ),
        migrations.CreateModel(
            name='HotKeys',
            fields=[
                ('keycode', models.IntegerField(primary_key=True, serialize=False)),
                ('equivalencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='acciones',
            name='hotkeys',
            field=models.ManyToManyField(to='posbys_config.HotKeys'),
        ),
    ]
